from __future__ import annotations

from ..project_tool_render import ProjectToolRenderMixin
from .project_tool_postparse_create_helpers import ProjectToolPostParseCreateHelpersMixin
from .project_tool_postparse_polish_helpers import ProjectToolPostParsePolishHelpersMixin
from .project_tool_postparse_silence_helpers import ProjectToolPostParseSilenceHelpersMixin
from .project_tool_postparse__parse_color import ProjectToolPostParseParseColorMixin
from .project_tool_postparse__draw_background_box import ProjectToolPostParseDrawBackgroundBoxMixin
from .project_tool_postparse__sanitize_text import ProjectToolPostParseSanitizeTextMixin
from .project_tool_postparse__get_opencc_converter import ProjectToolPostParseGetOpenccConverterMixin
from .project_tool_postparse__normalize_transcribed_text import ProjectToolPostParseNormalizeTranscribedTextMixin
from .project_tool_postparse__find_span_range import ProjectToolPostParseFindSpanRangeMixin
from .project_tool_postparse__wrap_by_pixel_width import ProjectToolPostParseWrapByPixelWidthMixin
from .project_tool_postparse__load_font import ProjectToolPostParseLoadFontMixin
from .project_tool_postparse__subtitle_y_position import ProjectToolPostParseSubtitleYPositionMixin
from .project_tool_postparse__subtitle_x_position import ProjectToolPostParseSubtitleXPositionMixin
from .project_tool_postparse__failure import ProjectToolPostParseFailureMixin
from .project_tool_postparse__load import ProjectToolPostParseLoadMixin
from .project_tool_postparse__probe_media import ProjectToolPostParseProbeMediaMixin
from .project_tool_postparse_create_project_from_media import ProjectToolPostParseCreateProjectFromMediaMixin
from .project_tool_postparse_load_project import ProjectToolPostParseLoadProjectMixin
from .project_tool_postparse_get_project_summary import ProjectToolPostParseGetProjectSummaryMixin
from .project_tool_postparse_search_project_subtitles import ProjectToolPostParseSearchProjectSubtitlesMixin
from .project_tool_postparse_list_project_clips import ProjectToolPostParseListProjectClipsMixin
from .project_tool_postparse_save_project import ProjectToolPostParseSaveProjectMixin
from .project_tool_postparse_trim_project_clip import ProjectToolPostParseTrimProjectClipMixin
from .project_tool_postparse_set_project_clip_speed import ProjectToolPostParseSetProjectClipSpeedMixin
from .project_tool_postparse_add_project_asset import ProjectToolPostParseAddProjectAssetMixin
from .project_tool_postparse_add_project_clip import ProjectToolPostParseAddProjectClipMixin
from .project_tool_postparse_add_project_subtitle import ProjectToolPostParseAddProjectSubtitleMixin
from .project_tool_postparse_update_project_subtitle import ProjectToolPostParseUpdateProjectSubtitleMixin
from .project_tool_postparse_remove_project_subtitle import ProjectToolPostParseRemoveProjectSubtitleMixin
from .project_tool_postparse_add_project_subtitle_span import ProjectToolPostParseAddProjectSubtitleSpanMixin
from .project_tool_postparse_update_project_subtitle_span import ProjectToolPostParseUpdateProjectSubtitleSpanMixin
from .project_tool_postparse_remove_project_subtitle_span import ProjectToolPostParseRemoveProjectSubtitleSpanMixin
from .project_tool_postparse_set_project_subtitle_effect import ProjectToolPostParseSetProjectSubtitleEffectMixin
from .project_tool_postparse_remove_project_subtitle_effect import ProjectToolPostParseRemoveProjectSubtitleEffectMixin
from .project_tool_postparse_batch_update_project_subtitles import ProjectToolPostParseBatchUpdateProjectSubtitlesMixin
from .project_tool_postparse_transcribe_audio import ProjectToolPostParseTranscribeAudioMixin
from .project_tool_postparse_remove_project_silence import ProjectToolPostParseRemoveProjectSilenceMixin
from .project_tool_postparse_detect_faces import ProjectToolPostParseDetectFacesMixin
from .project_tool_postparse_add_project_audio_stem import ProjectToolPostParseAddProjectAudioStemMixin
from .project_tool_postparse_update_project_audio_stem import ProjectToolPostParseUpdateProjectAudioStemMixin
from .project_tool_postparse_remove_project_audio_stem import ProjectToolPostParseRemoveProjectAudioStemMixin
from .project_tool_postparse_set_project_export_preset import ProjectToolPostParseSetProjectExportPresetMixin
from .project_tool_postparse_plan_project_export import ProjectToolPostParsePlanProjectExportMixin
from .project_tool_postparse_add_project_effect import ProjectToolPostParseAddProjectEffectMixin
from .project_tool_postparse_update_project_effect import ProjectToolPostParseUpdateProjectEffectMixin
from .project_tool_postparse_remove_project_effect import ProjectToolPostParseRemoveProjectEffectMixin
from .project_tool_postparse_generate_animejs_overlay_asset import ProjectToolPostParseGenerateAnimejsOverlayAssetMixin
from .project_tool_postparse_apply_overlay_to_screen import ProjectToolPostParseApplyOverlayToScreenMixin
from .project_tool_postparse_add_project_comment import ProjectToolPostParseAddProjectCommentMixin
from .project_tool_postparse_update_project_comment import ProjectToolPostParseUpdateProjectCommentMixin
from .project_tool_postparse_remove_project_comment import ProjectToolPostParseRemoveProjectCommentMixin
from .project_tool_postparse_lock_project_comment import ProjectToolPostParseLockProjectCommentMixin
from .project_tool_postparse_prepare_project_render import ProjectToolPostParsePrepareProjectRenderMixin
from .project_tool_postparse_set_project_metadata import ProjectToolPostParseSetProjectMetadataMixin
from .project_tool_postparse_set_project_clip_transform import ProjectToolPostParseSetProjectClipTransformMixin


class ProjectToolPostParseMixin(
    ProjectToolRenderMixin,
    ProjectToolPostParseCreateHelpersMixin,
    ProjectToolPostParsePolishHelpersMixin,
    ProjectToolPostParseSilenceHelpersMixin,
    ProjectToolPostParseParseColorMixin,
    ProjectToolPostParseDrawBackgroundBoxMixin,
    ProjectToolPostParseSanitizeTextMixin,
    ProjectToolPostParseGetOpenccConverterMixin,
    ProjectToolPostParseNormalizeTranscribedTextMixin,
    ProjectToolPostParseFindSpanRangeMixin,
    ProjectToolPostParseWrapByPixelWidthMixin,
    ProjectToolPostParseLoadFontMixin,
    ProjectToolPostParseSubtitleYPositionMixin,
    ProjectToolPostParseSubtitleXPositionMixin,
    ProjectToolPostParseFailureMixin,
    ProjectToolPostParseLoadMixin,
    ProjectToolPostParseProbeMediaMixin,
    ProjectToolPostParseCreateProjectFromMediaMixin,
    ProjectToolPostParseLoadProjectMixin,
    ProjectToolPostParseGetProjectSummaryMixin,
    ProjectToolPostParseSearchProjectSubtitlesMixin,
    ProjectToolPostParseListProjectClipsMixin,
    ProjectToolPostParseSaveProjectMixin,
    ProjectToolPostParseTrimProjectClipMixin,
    ProjectToolPostParseSetProjectClipSpeedMixin,
    ProjectToolPostParseAddProjectAssetMixin,
    ProjectToolPostParseAddProjectClipMixin,
    ProjectToolPostParseAddProjectSubtitleMixin,
    ProjectToolPostParseUpdateProjectSubtitleMixin,
    ProjectToolPostParseRemoveProjectSubtitleMixin,
    ProjectToolPostParseAddProjectSubtitleSpanMixin,
    ProjectToolPostParseUpdateProjectSubtitleSpanMixin,
    ProjectToolPostParseRemoveProjectSubtitleSpanMixin,
    ProjectToolPostParseSetProjectSubtitleEffectMixin,
    ProjectToolPostParseRemoveProjectSubtitleEffectMixin,
    ProjectToolPostParseBatchUpdateProjectSubtitlesMixin,
    ProjectToolPostParseTranscribeAudioMixin,
    ProjectToolPostParseRemoveProjectSilenceMixin,
    ProjectToolPostParseDetectFacesMixin,
    ProjectToolPostParseAddProjectAudioStemMixin,
    ProjectToolPostParseUpdateProjectAudioStemMixin,
    ProjectToolPostParseRemoveProjectAudioStemMixin,
    ProjectToolPostParseSetProjectExportPresetMixin,
    ProjectToolPostParsePlanProjectExportMixin,
    ProjectToolPostParseAddProjectEffectMixin,
    ProjectToolPostParseUpdateProjectEffectMixin,
    ProjectToolPostParseRemoveProjectEffectMixin,
    ProjectToolPostParseGenerateAnimejsOverlayAssetMixin,
    ProjectToolPostParseApplyOverlayToScreenMixin,
    ProjectToolPostParseAddProjectCommentMixin,
    ProjectToolPostParseUpdateProjectCommentMixin,
    ProjectToolPostParseRemoveProjectCommentMixin,
    ProjectToolPostParseLockProjectCommentMixin,
    ProjectToolPostParsePrepareProjectRenderMixin,
    ProjectToolPostParseSetProjectMetadataMixin,
    ProjectToolPostParseSetProjectClipTransformMixin,
):
    pass
