from .tool_setup_models import ToolSpec


def build_tool_specs() -> list[ToolSpec]:
    return [
        ToolSpec("project_core_contract", "Project Core Contract", "Structured guidance for reading tool outputs and staying inside the project core.", "project", "create_project_from_media", "project_core_contract.txt", register=False),
        ToolSpec("create_project_from_media", "Project Bootstrap Tool", "Create a project file directly from a raw video or audio source.", "project", "create_project_from_media", "create_project_from_media.txt"),
        ToolSpec("transcribe_audio", "Project Subtitle Transcription Tool", "Generate subtitle cues from source audio and store them in the project.", "project", "transcribe_audio", "transcribe_audio.txt"),
        ToolSpec("remove_project_silence", "Project Silence Removal Tool", "Rebuild the timeline by removing gaps between subtitle cues.", "project", "remove_project_silence", "remove_project_silence.txt"),
        ToolSpec("load_project", "Project Loader Tool", "Load a JSON or XML editing project.", "project", "load_project", "load_project.txt"),
        ToolSpec("get_project_summary", "Project Summary Tool", "Return a compact summary of project structure, timeline, and media counts.", "project", "get_project_summary", "get_project_summary.txt"),
        ToolSpec("search_project_subtitles", "Project Subtitle Search Tool", "Search subtitle cues by text, speaker, or language without loading the full project payload.", "project", "search_project_subtitles", "search_project_subtitles.txt"),
        ToolSpec("list_project_clips", "Project Clip List Tool", "List timeline clips with optional filters such as track, asset, and duration.", "project", "list_project_clips", "list_project_clips.txt"),
        ToolSpec("save_project", "Project Saver Tool", "Save a project back to JSON or XML.", "project", "save_project", "save_project.txt"),
        ToolSpec("set_project_metadata", "Project Metadata Tool", "Update project metadata in the unified project file.", "project", "set_project_metadata", "set_project_metadata.txt"),
        ToolSpec("trim_project_clip", "Project Clip Trim Tool", "Trim a clip inside a project file and save the updated project.", "project", "trim_project_clip", "trim_project_clip.txt"),
        ToolSpec("set_project_clip_speed", "Project Clip Speed Tool", "Update clip speed inside a project file.", "project", "set_project_clip_speed", "set_project_clip_speed.txt"),
        ToolSpec("set_project_clip_transform", "Project Clip Transform Tool", "Update clip position, scale, opacity, and transform data inside a project file.", "project", "set_project_clip_transform", "set_project_clip_transform.txt"),
        ToolSpec("add_project_asset", "Project Asset Tool", "Add a media asset into a project file.", "project", "add_project_asset", "add_project_asset.txt"),
        ToolSpec("add_project_clip", "Project Clip Insert Tool", "Insert a clip that references an existing asset onto a timeline track at a specific time range.", "project", "add_project_clip", "add_project_clip.txt"),
        ToolSpec("generate_animejs_overlay_asset", "Anime.js Overlay Asset Tool", "Store Anime.js source and register a compact transparent sticker or effect overlay asset in the project.", "project", "generate_animejs_overlay_asset", "generate_animejs_overlay_asset.txt"),
        ToolSpec("apply_overlay_to_screen", "Overlay Screen Placement Tool", "Place a transparent overlay asset onto the timeline at a specific time and screen position over a target clip.", "project", "apply_overlay_to_screen", "apply_overlay_to_screen.txt"),
        ToolSpec("add_project_subtitle", "Project Subtitle Add Tool", "Add a subtitle cue into a project file, including spans, position, and margins.", "project", "add_project_subtitle", "add_project_subtitle.txt"),
        ToolSpec("update_project_subtitle", "Project Subtitle Update Tool", "Update a subtitle cue inside a project file, including spans, position, and margins.", "project", "update_project_subtitle", "update_project_subtitle.txt"),
        ToolSpec("batch_update_project_subtitles", "Project Subtitle Batch Styling Tool", "Update many subtitle cues in one call, including positions, spans, and multiple subtitle effects per cue.", "project", "batch_update_project_subtitles", "batch_update_project_subtitles.txt"),
        ToolSpec("add_project_subtitle_span", "Project Subtitle Span Add Tool", "Add a styled span into one subtitle cue.", "project", "add_project_subtitle_span", "add_project_subtitle_span.txt"),
        ToolSpec("update_project_subtitle_span", "Project Subtitle Span Update Tool", "Update the text or style of one subtitle span.", "project", "update_project_subtitle_span", "update_project_subtitle_span.txt"),
        ToolSpec("remove_project_subtitle_span", "Project Subtitle Span Remove Tool", "Remove one subtitle span from a cue.", "project", "remove_project_subtitle_span", "remove_project_subtitle_span.txt"),
        ToolSpec("remove_project_subtitle", "Project Subtitle Remove Tool", "Remove a subtitle cue from a project file.", "project", "remove_project_subtitle", "remove_project_subtitle.txt"),
        ToolSpec("prepare_project_render", "Project Render Planning Tool", "Validate a project and produce render readiness state.", "project", "prepare_project_render", "prepare_project_render.txt"),
        ToolSpec("add_project_audio_stem", "Project Audio Stem Add Tool", "Add an audio stem reference to a project file.", "project", "add_project_audio_stem", "add_project_audio_stem.txt"),
        ToolSpec("update_project_audio_stem", "Project Audio Stem Update Tool", "Update an audio stem in a project file.", "project", "update_project_audio_stem", "update_project_audio_stem.txt"),
        ToolSpec("remove_project_audio_stem", "Project Audio Stem Remove Tool", "Remove an audio stem from a project file.", "project", "remove_project_audio_stem", "remove_project_audio_stem.txt"),
        ToolSpec("set_project_export_preset", "Project Export Preset Tool", "Create or update an export preset in a project file.", "project", "set_project_export_preset", "set_project_export_preset.txt"),
        ToolSpec("plan_project_export", "Project Export Planning Tool", "Plan preview, final, and sidecar export paths for a project.", "project", "plan_project_export", "plan_project_export.txt"),
        ToolSpec("render_project", "Project Render Tool", "Render the project timeline to a final video file with subtitle burn-in.", "project", "render_project", "render_project.txt"),
        ToolSpec("add_project_effect", "Project Effect Add Tool", "Add a visual effect to a project file.", "project", "add_project_effect", "add_project_effect.txt"),
        ToolSpec("update_project_effect", "Project Effect Update Tool", "Update a visual effect in a project file.", "project", "update_project_effect", "update_project_effect.txt"),
        ToolSpec("remove_project_effect", "Project Effect Remove Tool", "Remove a visual effect from a project file.", "project", "remove_project_effect", "remove_project_effect.txt"),
        ToolSpec("set_project_subtitle_effect", "Project Subtitle Effect Tool", "Attach a visual or animation effect to a subtitle cue.", "project", "set_project_subtitle_effect", "set_project_subtitle_effect.txt"),
        ToolSpec("remove_project_subtitle_effect", "Project Subtitle Effect Remove Tool", "Remove one or all effects from a subtitle cue.", "project", "remove_project_subtitle_effect", "remove_project_subtitle_effect.txt"),
        ToolSpec("add_project_comment", "Project Comment Add Tool", "Add a collaboration comment to a project file.", "project", "add_project_comment", "add_project_comment.txt"),
        ToolSpec("update_project_comment", "Project Comment Update Tool", "Update an existing project comment.", "project", "update_project_comment", "update_project_comment.txt"),
        ToolSpec("remove_project_comment", "Project Comment Remove Tool", "Remove a collaboration comment from a project file.", "project", "remove_project_comment", "remove_project_comment.txt"),
        ToolSpec("lock_project_comment", "Project Comment Lock Tool", "Lock or unlock a collaboration comment.", "project", "lock_project_comment", "lock_project_comment.txt"),
        ToolSpec("detect_faces", "Face Detection Tool", "Detect faces in a project's source video and return their bounding box positions per sampled frame.", "project", "detect_faces", "detect_faces.txt"),
        ToolSpec("vision_analyze_media", "Vision Analyze Media Tool", "Analyze an image or video with an OpenAI-compatible vision model.", "vision", "vision_analyze_media", "vision_analyze_media.txt"),
        ToolSpec("search_net_asset", "Network Asset Search Tool", "Search online stock libraries for free-to-use assets.", "net_asset", "search_net_asset", "search_net_asset.txt"),
        ToolSpec("download_net_asset", "Network Asset Download Tool", "Download a stock asset from a URL returned by search_net_asset.", "net_asset", "download_net_asset", "download_net_asset.txt"),
    ]
