from .tool_setup_models import SkillSpec, ToolSpec


def build_skill_specs(specs: list[ToolSpec]) -> dict[str, SkillSpec]:
    return {
        "full": SkillSpec("full", "Full Editing Skill", "All tools are available. Use this only when the task spans project editing, asset discovery, vision, or CapCut finalization.", [spec.name for spec in specs if spec.register], doc_names=["project_core_contract"], keywords=["all tools", "everything", "full", "complete", "general"]),
        "workflow_orchestrator": SkillSpec("workflow_orchestrator", "Workflow Orchestrator Skill", "Plan multi-stage tasks, load the next skill, compress context between stages, and emit nudges for multi-skill workflows.", [], doc_names=["workflow_orchestrator"], keywords=["plan", "orchestrate", "workflow", "multi-step", "handoff", "stage", "pipeline"]),
        "project_core": SkillSpec("project_core", "Project Core Skill", "Core project editing tools for loading, updating, validating, and rendering projects.", ["create_project_from_media", "transcribe_audio", "remove_project_silence", "load_project", "get_project_summary", "search_project_subtitles", "list_project_clips", "save_project", "set_project_metadata", "trim_project_clip", "set_project_clip_speed", "add_project_asset", "add_project_clip", "add_project_subtitle", "update_project_subtitle", "batch_update_project_subtitles", "add_project_subtitle_span", "update_project_subtitle_span", "remove_project_subtitle_span", "remove_project_subtitle", "prepare_project_render", "add_project_audio_stem", "update_project_audio_stem", "remove_project_audio_stem", "set_project_export_preset", "plan_project_export", "render_project", "add_project_effect", "update_project_effect", "remove_project_effect", "set_project_subtitle_effect", "remove_project_subtitle_effect", "add_project_comment", "update_project_comment", "remove_project_comment", "lock_project_comment", "detect_faces"], doc_names=["project_core_contract"], keywords=["project", "subtitle", "captions", "trim", "clip", "render", "export", "load", "save", "metadata", "transcribe", "silence", "timeline", "错别字", "修复字幕", "字幕", "位置", "样式", "高亮", "关键词", "改字幕"]),
        "asset_discovery": SkillSpec("asset_discovery", "Asset Discovery Skill", "Search and download stock assets for use in a project.", ["search_net_asset", "download_net_asset"], keywords=["search", "download", "asset", "stock", "pexels", "pixabay", "freesound"]),
        "vision_inspection": SkillSpec("vision_inspection", "Vision Inspection Skill", "Inspect image or video content and extract visual observations.", ["vision_analyze_media"], keywords=["vision", "inspect", "analyze", "analysis", "image", "video", "media", "ocr", "frame", "scene", "summary", "visual", "识别", "画面", "视频分析", "图片分析"]),
        "capcut_finalization": SkillSpec("capcut_finalization", "CapCut Finalization Skill", "Handle post-render CapCut work only.", ["capcut_video_creation"], keywords=["capcut", "draft", "sticker", "effect", "post-render", "finalize", "剪映", "草稿", "特效", "贴纸", "后期"]),
    }
